### ISSUE TITLE
[HEVC] Include `-tag:v hvc1` for improved compatibility with Apple devices

### ISSUE THREAD

**Issue by blampe** [revenz/FileFlowsPlugins#12]
`ffmpeg` defaults to `hev1` if unspecified, but `hvc1` has [better compatibility](https://developer.apple.com/documentation/http-live-streaming/hls-authoring-specification-for-apple-devices#Video) with Apple devices. 

> 1.10. You SHOULD use video formats in which the parameter sets are stored in the sample descriptions, rather than the samples. (That is, use 'avc1', 'hvc1', or 'dvh1' rather than 'avc3', 'hev1', or 'dvhe'.)

Out of the box, the HEVC encoder produces MP4s that don't play on MacOS. They play fine after fixing the tag with `ffmpeg -vcodec copy -acodec copy -tag:v hvc1 ...`, however.

**Comment by revenz** [comment]
this is not the place for issues. closing and turning off issues
